# Generated by Django 4.2.17 on 2025-02-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(max_length=10, unique=True, verbose_name='PAN No.')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('related_company', models.CharField(max_length=255, verbose_name='Related Company')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('valid_till_date', models.DateField(verbose_name='Valid Till Date')),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing Authority')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('position', models.CharField(choices=[('individual', 'Individual'), ('director', 'Director'), ('partner', 'Partner')], max_length=20, verbose_name='Select Position')),
                ('class_type', models.CharField(choices=[('class_type_1', 'Class type 1'), ('class_type_2', 'Class type 2'), ('class_type_3', 'Class type 3')], max_length=20, verbose_name='Class Type')),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile No.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('custodian_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custodian Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcs_created_customers', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcs_updated_customers', to='custom_auth.customuser')),
            ],
        ),
    ]
