# Generated by Django 4.2.17 on 2025-02-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_account_manager_customer_accountant_name_and_more'),
        ('dcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdcs',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcs_customer', to='clients.customer'),
        ),
    ]
