# Generated by Django 4.2.17 on 2025-03-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='add_signature_to_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
