# Generated by Django 4.2.17 on 2025-02-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to='custom_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='reportinguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reporting_details', serialize=False, to='custom_auth.customuser'),
        ),
    ]
