# Generated by Django 4.2.17 on 2025-02-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0010_alter_clientworkcategoryassignment_priority'),
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_amount', models.FloatField(blank=True, default=0, null=True)),
                ('expense_date', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_updated', to='custom_auth.customuser')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_expense', to='workflow.clientworkcategoryassignment')),
            ],
        ),
    ]
