# Generated by Django 4.2.17 on 2025-02-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_rename_dcs_customer_dsc'),
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
        ('expense', '0001_initial'),
        ('workflow', '0011_clientworkcategoryassignment_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('adhoc', 'AD-HOC'), ('structured', 'Structured')], default='adhoc', max_length=20)),
                ('billing_company', models.CharField(max_length=255, verbose_name='Billing Company')),
                ('bank', models.CharField(max_length=255, verbose_name='Bank')),
                ('financial_year', models.CharField(max_length=10, verbose_name='Financial Year')),
                ('type_of_supply', models.CharField(choices=[('b2b', 'B2B'), ('sezwp', 'SEZWP'), ('sezwop', 'SEZWOP'), ('expwop', 'EXPWOP'), ('dexp', 'DEXP'), ('b2c', 'B2C')], default='b2b', max_length=10, verbose_name='Type Of Supply')),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place Of Supply')),
                ('billing_description', models.TextField(verbose_name='Billing Description')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fees')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('proforma_invoice', models.BooleanField(default=False, verbose_name='Proforma Invoice')),
                ('requested_by', models.CharField(max_length=255, verbose_name='Requested By')),
                ('narration', models.TextField(verbose_name='Narration')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST(18%)')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GST amount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('round_off', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Round Off')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount')),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unpaid Amount')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially-paid', 'Partially-paid'), ('paid', 'Paid')], default='unpaid', max_length=50)),
                ('reverse_charges', models.BooleanField(default=False, verbose_name='Reverse Charges')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_created', to='custom_auth.customuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bill', to='clients.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_updated', to='custom_auth.customuser')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('deposit_to', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('receipt_no', models.CharField(max_length=100, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unsettled_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipt', to='clients.customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_updated', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('waived_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_details', to='billing.billing')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_invoice', to='billing.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_description', models.CharField(max_length=255, null=True, verbose_name='expense_description')),
                ('expense_type', models.CharField(max_length=255, null=True, verbose_name='expense_type')),
                ('hsn_code', models.CharField(max_length=255, null=True, verbose_name='hsn_code')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expense Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='billing.billing')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_item', to='expense.expense')),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255, null=True, verbose_name='task_name')),
                ('hsn_code', models.CharField(max_length=255, null=True, verbose_name='task_name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='billing.billing')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_task', to='workflow.clientworkcategoryassignment')),
            ],
        ),
    ]
