# Generated by Django 4.2.17 on 2025-02-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptinvoice',
            name='outstanding_amount',
        ),
    ]
