# Generated by Django 4.2.17 on 2025-02-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
        ('clients', '0003_rename_dcs_customer_dsc'),
        ('billing', '0002_remove_receiptinvoice_outstanding_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_company', models.CharField(max_length=255, verbose_name='Billing Company')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Company')),
                ('type_of_supply', models.CharField(max_length=100, verbose_name='Type Of Supply')),
                ('place_of_supply', models.CharField(max_length=100, verbose_name='Place Of Supply')),
                ('credit_note_date', models.DateField(verbose_name='Credit Note Date')),
                ('bill_no_to_be_adjusted', models.CharField(max_length=100, verbose_name='Bill No. to be Adjusted')),
                ('gst', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST (%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('credit_note_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Credit Note Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_created_by', to='custom_auth.customuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit', to='clients.customer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_updated_by', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_company', models.CharField(max_length=255, verbose_name='Billing Company')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('type_of_supply', models.CharField(max_length=100, verbose_name='Type Of Supply')),
                ('place_of_supply', models.CharField(max_length=100, verbose_name='Place Of Supply')),
                ('debit_note_date', models.DateField(verbose_name='Debit Note Date')),
                ('bill_no_to_be_adjusted', models.CharField(max_length=100, verbose_name='Bill No. to be Adjusted')),
                ('gst', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST (%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('debit_note_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Debit Note Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_created_by', to='custom_auth.customuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debit', to='clients.customer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_updated_by', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('hsn_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='HSN No.')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.debitnote', verbose_name='Debit Note')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('hsn_no', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.creditnote', verbose_name='Credit Note')),
            ],
        ),
    ]
