# Generated by Django 4.2.17 on 2025-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditnote_debitnote_debitnoteitem_creditnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(choices=[('sales_return', 'Sales Return'), ('post_sales_discount', 'Post sales Discount'), ('deficiency_in_service', 'Deficiency In Service'), ('correction_in_invoice', 'Correction in invoice'), ('change_in_pos', 'Change in POS'), ('finalization_of_provisional_assessment', 'Finalization of provisional Assessment'), ('others', 'Others')], default='others', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='type_of_supply',
            field=models.CharField(choices=[('b2b', 'B2B'), ('sezwp', 'SEZWP'), ('sezwop', 'SEZWOP'), ('expwop', 'EXPWOP'), ('dexp', 'DEXP'), ('b2c', 'B2C')], max_length=100, verbose_name='Type Of Supply'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='reason',
            field=models.CharField(blank=True, choices=[('sales_return', 'Sales Return'), ('post_sales_discount', 'Post sales Discount'), ('deficiency_in_service', 'Deficiency In Service'), ('correction_in_invoice', 'Correction in invoice'), ('change_in_pos', 'Change in POS'), ('finalization_of_provisional_assessment', 'Finalization of provisional Assessment'), ('others', 'Others')], max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='type_of_supply',
            field=models.CharField(choices=[('b2b', 'B2B'), ('sezwp', 'SEZWP'), ('sezwop', 'SEZWOP'), ('expwop', 'EXPWOP'), ('dexp', 'DEXP'), ('b2c', 'B2C')], max_length=100, verbose_name='Type Of Supply'),
        ),
    ]
