# Generated by Django 4.2.17 on 2025-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_creditnote_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='hrs_spent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='include_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='task',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Narration'),
        ),
    ]
