# Generated by Django 4.2.17 on 2025-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billing_hrs_spent_billing_include_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='final_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount'),
        ),
    ]
