# Generated by Django 4.2.17 on 2025-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billing_final_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='CGST(9%)'),
        ),
        migrations.AddField(
            model_name='billing',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='CGST_amount'),
        ),
        migrations.AddField(
            model_name='billing',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='SGST(9%)'),
        ),
        migrations.AddField(
            model_name='billing',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SGST amount'),
        ),
    ]
