# Generated by Django 4.2.17 on 2025-04-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billing_cgst_billing_cgst_amount_billing_sgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
