# Generated by Django 4.2.17 on 2025-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='narration'),
        ),
        migrations.AlterField(
            model_name='billitems',
            name='hsn_code',
            field=models.CharField(max_length=255, null=True, verbose_name='hsn_code'),
        ),
    ]
