# Generated by Django 4.2.17 on 2025-01-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_updated', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_created', to='custom_auth.customuser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_categories', to='workflow.department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_updated', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategoryUploadDocumentRequired',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_documentrequired_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_documentrequired_updated', to='custom_auth.customuser')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_document', to='workflow.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategoryFilesRequired',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_filesrequired_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_filesrequired_updated', to='custom_auth.customuser')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_required', to='workflow.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategoryActivityList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_activitylist_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_activitylist_updated', to='custom_auth.customuser')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_list', to='workflow.workcategory')),
            ],
        ),
    ]
