# Generated by Django 4.2.17 on 2025-01-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorkCategoryAssignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_category_assignments', to='clients.customer')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflow.workcategory')),
            ],
        ),
    ]
