# Generated by Django 4.2.17 on 2025-01-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
        ('workflow', '0002_clientworkcategoryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_assignments_created', to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_assignments', to='custom_auth.customuser'),
        ),
    ]
