# Generated by Django 4.2.17 on 2025-02-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
        ('clients', '0002_rename_account_manager_customer_accountant_name_and_more'),
        ('workflow', '0003_clientworkcategoryassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workcategoryactivitylist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workcategoryfilesrequired',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workcategoryuploaddocumentrequired',
            name='description',
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='allocated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_assignments_created', to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='priority',
            field=models.IntegerField(choices=[('pending_from_client_side', 'Pending from Client Side'), ('details_received_but_work_not_started', 'Details Received but Work Not Started'), ('work_in_progress', 'Work in Progress'), ('task_under_review', 'Task Under Review'), ('pending_sr_review', 'Pending SR. Review'), ('sr_review_completed', 'SR. Review Completed'), ('task_completed', 'Task Completed'), ('task_billed', 'Task Billed'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('task_closed', 'Task Closed')], default=1),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='progress',
            field=models.CharField(choices=[('pending_from_client_side', 'Pending from Client Side'), ('details_received_but_work_not_started', 'Details Received but Work Not Started'), ('work_in_progress', 'Work in Progress'), ('task_under_review', 'Task Under Review'), ('pending_sr_review', 'Pending SR. Review'), ('sr_review_completed', 'SR. Review Completed'), ('task_completed', 'Task Completed'), ('task_billed', 'Task Billed'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('task_closed', 'Task Closed')], default='pending_from_client_side', max_length=100),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='review_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_reviewed', to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='review_notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_assignments_updated', to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='workcategoryactivitylist',
            name='assigned_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientworkcategoryassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category_assignments_assigned', to='custom_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='clientworkcategoryassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_category_customer', to='clients.customer'),
        ),
        migrations.CreateModel(
            name='AssignedWorkRequiredFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_files', to='workflow.clientworkcategoryassignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedWorkOutputFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='workflow.clientworkcategoryassignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedWorkActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
                ('assigned_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.clientworkcategoryassignment')),
            ],
        ),
    ]
