# Generated by Django 4.2.17 on 2025-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_workcategory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientworkcategoryassignment',
            old_name='id',
            new_name='assignment_id',
        ),
        migrations.AlterField(
            model_name='assignedworkactivity',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedworkoutputfiles',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignedworkrequiredfiles',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
