# Generated by Django 4.2.17 on 2025-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_rename_id_clientworkcategoryassignment_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedworkactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignedworkoutputfiles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignedworkrequiredfiles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientworkcategoryassignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workcategoryactivitylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workcategoryfilesrequired',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workcategoryuploaddocumentrequired',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
