# Generated by Django 4.2.17 on 2025-02-06 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
        ('workflow', '0006_alter_assignedworkactivity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcategory',
            name='fees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='WorkCategoryActivityStages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_stage', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_activitystage_created', to='custom_auth.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcategories_activitystage_updated', to='custom_auth.customuser')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stage', to='workflow.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedWorkActivityStages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stages', to='workflow.clientworkcategoryassignment')),
            ],
        ),
    ]
