# Generated by Django 4.2.17 on 2025-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workcategory_fees_workcategoryactivitystages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedworkactivity',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
