# Generated by Django 4.2.17 on 2025-02-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
        ('workflow', '0008_assignedworkactivity_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_manager', to='custom_auth.customuser'),
        ),
    ]
