# Generated by Django 4.2.17 on 2025-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientworkcategoryassignment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1),
        ),
    ]
