# Generated by Django 4.2.17 on 2025-02-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_clientworkcategoryassignment_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='instructions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='task_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
