# Generated by Django 4.2.17 on 2025-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_clientworkcategoryassignment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedworkactivity',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignedworkactivitystages',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignedworkoutputfiles',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignedworkrequiredfiles',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workcategoryactivitylist',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workcategoryactivitystages',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workcategoryfilesrequired',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workcategoryuploaddocumentrequired',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
