# Generated by Django 4.2.17 on 2025-03-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_customercontacts_mobile'),
        ('custom_auth', '0005_alter_customuser_address'),
        ('workflow', '0013_workcategory_frequency_workcategory_start_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTaskTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mode_of_communication', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_schedule', to='custom_auth.customuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_schedule', to='custom_auth.customuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutomer_schedule_time', to='clients.customer')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_schedule', to='workflow.clientworkcategoryassignment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_schedule', to='custom_auth.customuser')),
            ],
        ),
    ]
