# Generated by Django 4.2.17 on 2025-03-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_scheduletasktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworkcategoryassignment',
            name='is_repetitive',
            field=models.BooleanField(default=False),
        ),
    ]
