# Generated by Django 4.2.17 on 2025-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_clientworkcategoryassignment_is_repetitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletasktime',
            name='activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduletasktime',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
