# Generated by Django 4.2.17 on 2025-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_alter_clientworkreminder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedworkactivity',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
