# Generated by Django 4.2.17 on 2025-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('business_pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('constitution', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('llipin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('din_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('enable_account', models.BooleanField(default=True)),
                ('account_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
