# Generated by Django 4.2.17 on 2025-02-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_employeeprofile_customuser_employee_code_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_manager',
            new_name='accountant_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='destination_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='accountant_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_created_by', to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dcs',
            field=models.CharField(blank=True, choices=[('new_dcs', 'New DCS'), ('received', 'Received'), ('not_received', 'Not Received'), ('na', 'NA')], default='na', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='file_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('proprietor', 'Proprietor'), ('firm', 'Firm'), ('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('bank', 'Bank'), ('aop_or_boi', 'AOP Or BOI'), ('huf', 'HUF'), ('ajp', 'AJP'), ('society', 'Society')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_updated_by', to='custom_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
