# Generated by Django 4.2.17 on 2025-02-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_account_manager_customer_accountant_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dcs',
            new_name='dsc',
        ),
    ]
