# Generated by Django 4.2.17 on 2025-03-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_customer_destination_address_alter_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontacts',
            name='mobile',
        ),
    ]
