# Generated by Django 4.2.17 on 2025-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_customercontacts_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_services', models.CharField(blank=True, max_length=255, null=True)),
                ('other_services', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
