# Generated by Django 4.2.17 on 2025-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='call_email_id',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='call_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='call_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='otp_email_id',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='otp_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='otp_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_email_id',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
