# Generated by Django 4.2.17 on 2025-04-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_inquiry_call_email_id_inquiry_call_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='call_email_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='otp_email_id',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='call_relation',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='otp_relation',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
