# Generated by Django 4.2.17 on 2025-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_inquiry_call_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='call_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='otp_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='reference_email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
