# Generated by Django 4.2.17 on 2025-04-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_inquiry_call_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dsc',
            field=models.CharField(blank=True, choices=[('new_dcs', 'New DSC'), ('received', 'Received'), ('not_received', 'Not Received'), ('na', 'NA')], default='na', max_length=50, null=True),
        ),
    ]
