# Generated by Django 4.2.17 on 2025-02-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
        ('importexport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inward_created', to='custom_auth.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inward',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inward',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inward_modified', to='custom_auth.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inward',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inward',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
