# Generated by Django 4.2.17 on 2025-02-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
        ('clients', '0002_rename_account_manager_customer_accountant_name_and_more'),
        ('importexport', '0002_inward_created_by_inward_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_reference', models.CharField(choices=[('non-inward-entry', 'Non-Inward Entry'), ('inward-entry', 'Inward Entry')], max_length=50, verbose_name='Outward Reference')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('outward_title', models.CharField(max_length=120, verbose_name='Outward Title')),
                ('about_outward', models.TextField(verbose_name='About Outward')),
                ('outward_through', models.CharField(choices=[('by_courier', 'By Courier'), ('hand_over_to_client', 'Hand over to client in-person'), ('sent_via_office_boy', 'Sent Via Office Boy')], max_length=100, verbose_name='Outward Through')),
                ('avb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_person', models.CharField(blank=True, max_length=100, null=True)),
                ('outward_date', models.DateField(verbose_name='Outward Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_created', to='custom_auth.customuser', verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_customer', to='clients.customer', verbose_name='Customer')),
                ('inward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_inward', to='importexport.inward', verbose_name='Inward Entry')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_modified', to='custom_auth.customuser', verbose_name='Modified By')),
            ],
        ),
    ]
