# Generated by Django 4.2.17 on 2025-03-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_workcategory_frequency_workcategory_start_dates_and_more'),
        ('importexport', '0003_outward'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_for_task', to='workflow.clientworkcategoryassignment'),
        ),
    ]
