# Generated by Django 4.2.17 on 2025-02-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_department_manager'),
        ('clients', '0002_rename_account_manager_customer_accountant_name_and_more'),
        ('custom_auth', '0003_alter_employeeprofile_user_alter_reportinguser_user'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_on_client', to='clients.customer'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_for_work', to='workflow.clientworkcategoryassignment'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='work_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_for_activity', to='workflow.assignedworkactivity'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='custom_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='custom_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='task_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='task_type',
            field=models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non Billable')], default='non_billable', max_length=20),
        ),
    ]
